// Mock data for ChatLens — a 3-column chat intelligence viewer
// Scenario: a daemon collecting messages from multiple AI/ML signal sources

window.DATA = (() => {
  const channels = [
    { id: 'ai-twitter',    name: 'ai-twitter',     icon: 'X',  count: 247, source: 'twitter'  },
    { id: 'hn-frontpage',  name: 'hn-frontpage',   icon: 'Y',  count: 38,  source: 'hn'       },
    { id: 'discord-ml',    name: 'discord-ml',     icon: 'D',  count: 184, source: 'discord'  },
    { id: 'arxiv-daily',   name: 'arxiv-daily',    icon: 'A',  count: 62,  source: 'arxiv'    },
    { id: 'github-issues', name: 'github-issues',  icon: 'G',  count: 91,  source: 'github'   },
  ];

  // Messages per channel. Each message: id, user, time, content, priority, image?, refs?
  // refs[] = topic IDs this message is a source for (used for L1→L2 linking)
  // priority: 'high' | 'med' | 'low'
  const messages = {
    'ai-twitter': [
      { id: 'm101', day: 'Today',     time: '14:32', user: 'swyx',         av: 1, pri: 'high', refs: ['t1'],
        text: 'Confirmed: GPT-5 system card leaked from a partner. Multi-modal native, 400k context, agentic loop baked in. Page 14 has the eval numbers, this is real.' },
      { id: 'm102', day: 'Today',     time: '14:38', user: 'karpathy',     av: 2, pri: 'high', refs: ['t1'],
        text: 'Eval table from the leak — these MMLU + SWE-bench numbers look genuine. The interleaving scheme is interesting, not just CoT.', 
        image: { src: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&q=80', w: 280, h: 158, caption: 'eval_table.png · 412 KB' } },
      { id: 'm103', day: 'Today',     time: '14:41', user: 'sama_unofficial', av: 5, pri: 'low',
        text: 'lol this is the third "leak" this month' },
      { id: 'm104', day: 'Today',     time: '14:43', user: 'gdb',          av: 3, pri: 'med', refs: ['t1'],
        text: 'No comment. (No comment is a comment.)' },
      { id: 'm105', day: 'Today',     time: '14:47', user: 'jeremyphoward',av: 4, pri: 'low',
        text: 'people are reading way too much into a screenshot. wait for the announcement.' },
      { id: 'm106', day: 'Today',     time: '15:02', user: 'thursdayai',   av: 6, pri: 'med', refs: ['t1'],
        text: 'Pinned: rumor consolidation thread. ETA still pointing at next Tuesday based on partner NDAs expiring.' },
      { id: 'm107', day: 'Today',     time: '15:14', user: 'anthropic_ai', av: 7, pri: 'high', refs: ['t2'],
        text: 'Claude now supports custom tool execution environments via the Containers API. Public beta starts today, generous free tier through Q3.' },
      { id: 'm108', day: 'Today',     time: '15:16', user: 'simonw',       av: 8, pri: 'high', refs: ['t2'],
        text: 'Already running my code-review agent in a sandboxed container. Setup was ~6 lines. This is the missing piece for agent reliability.' },
      { id: 'm109', day: 'Today',     time: '15:22', user: 'ldjconfirmed', av: 1, pri: 'med', refs: ['t2'],
        text: 'Pricing: $0.10/hour per active container, 50 free hours/month. Aggressive vs Modal/Fly.' },
      { id: 'm110', day: 'Today',     time: '15:38', user: 'main',         av: 2, pri: 'low',
        text: 'gm' },
      { id: 'm111', day: 'Today',     time: '15:41', user: 'main',         av: 2, pri: 'low',
        text: 'gn' },
      { id: 'm112', day: 'Today',     time: '15:55', user: 'pat_anthropic',av: 7, pri: 'med', refs: ['t3'],
        text: 'MCP adoption now at 14k+ servers indexed. Mostly dev tools but seeing real growth in finance and legal verticals.' },
      { id: 'm113', day: 'Today',     time: '16:02', user: 'mckaywrigley', av: 3, pri: 'med', refs: ['t3'],
        text: 'My MCP directory hit 9k weekly actives. Up 4x in 8 weeks. Mostly cursor + claude desktop users.' },
      { id: 'm114', day: 'Today',     time: '16:10', user: 'main',         av: 2, pri: 'low',
        text: 'is the api down again?' },
      { id: 'm115', day: 'Today',     time: '16:11', user: 'main',         av: 2, pri: 'low',
        text: 'nvm' },
      { id: 'm116', day: 'Today',     time: '16:24', user: 'finbarrtimbers', av: 5, pri: 'med', refs: ['t4'],
        text: 'Open question that nobody is answering: how do we benchmark agents when the task itself is dynamic? GAIA is saturating, SWE-bench is gameable.' },
      { id: 'm117', day: 'Today',     time: '16:31', user: 'aman_sanger',  av: 4, pri: 'med', refs: ['t4'],
        text: 'agree. internal evals are diverging from public benchmarks. need a "moving target" eval framework.' },
      { id: 'm118', day: 'Today',     time: '16:45', user: 'yi_tay',       av: 6, pri: 'low',
        text: 'every benchmark eventually becomes a training target. that is just how it goes.' },
      { id: 'm119', day: 'Today',     time: '17:08', user: 'soumithchintala', av: 1, pri: 'high', refs: ['t5'],
        text: 'PyTorch 2.6 dropped. compile() now 1.7x faster on H100 for transformer inference. flash-attn v3 default.' },
      { id: 'm120', day: 'Today',     time: '17:11', user: 'main',         av: 2, pri: 'low',
        text: 'finally' },
    ],
    'hn-frontpage': [
      { id: 'h201', day: 'Today',     time: '13:02', user: 'dang',         av: 1, pri: 'high', refs: ['t1'],
        text: 'Submission: "GPT-5 system card (mirror)" — 1.2k points, 480 comments. Front page #1.' },
      { id: 'h202', day: 'Today',     time: '13:42', user: 'jefftk',       av: 3, pri: 'med', refs: ['t2'],
        text: 'Claude Containers — comments are mostly positive, devs comparing to E2B and asking about cold start latency.' },
      { id: 'h203', day: 'Today',     time: '14:15', user: 'patio11',      av: 4, pri: 'low',
        text: 'Re: container pricing thread — usual gripes about lock-in but most agree the numbers are competitive.' },
      { id: 'h204', day: 'Today',     time: '15:30', user: 'tptacek',      av: 7, pri: 'med', refs: ['t4'],
        text: '"Benchmarks are lies, evals are theatre" — opinion piece climbing. Cites SWE-bench leakage paper.' },
    ],
    'discord-ml':    [
      { id: 'd301', day: 'Today',     time: '14:55', user: 'researcher42', av: 5, pri: 'med', refs: ['t1'],
        text: 'in #rumors — vibes are that the leak is real but the eval table is partial. 400k context is the headline.' },
      { id: 'd302', day: 'Today',     time: '15:20', user: 'agent_dev',    av: 6, pri: 'high', refs: ['t2'],
        text: 'just migrated our coding agent to Claude Containers. cold start ~800ms, way under our 2s budget.' },
      { id: 'd303', day: 'Today',     time: '15:48', user: 'agent_dev',    av: 6, pri: 'low',
        text: 'also they have a generous free tier so go nuts' },
      { id: 'd304', day: 'Today',     time: '16:30', user: 'mcp_curator',  av: 8, pri: 'med', refs: ['t3'],
        text: 'MCP server count this week: github (+340), notion (+210), linear (+88). Bulk of growth still dev tools.' },
    ],
    'arxiv-daily':   [
      { id: 'a401', day: 'Today',     time: '09:00', user: 'arxiv-bot',    av: 8, pri: 'med', refs: ['t4'],
        text: 'New: "Dynamic Task Benchmarking for LLM Agents" (Stanford + DeepMind). Proposes moving-target evals where the task spec is regenerated each run.' },
      { id: 'a402', day: 'Today',     time: '09:00', user: 'arxiv-bot',    av: 8, pri: 'low',
        text: 'New: "Attention is Still All You Need: 7 Years Later" — survey paper, 84 pages.' },
      { id: 'a403', day: 'Today',     time: '09:00', user: 'arxiv-bot',    av: 8, pri: 'med', refs: ['t5'],
        text: 'New: "Speculative Decoding for Long Context: A 1.8x Throughput Win on H100". Implementation drops landing in PyTorch 2.6.' },
    ],
    'github-issues': [
      { id: 'g501', day: 'Today',     time: '12:00', user: 'anthropics/sdk', av: 2, pri: 'high', refs: ['t2'],
        text: '#4421 opened: Containers API beta — official tracking issue. 14 thumbs, 6 comments in first hour.' },
      { id: 'g502', day: 'Today',     time: '15:30', user: 'pytorch/pytorch', av: 1, pri: 'high', refs: ['t5'],
        text: 'v2.6.0 tagged. Release notes: 184 changes. compile() improvements, flash-attn v3, sparse MoE kernels.' },
    ],
  };

  // Topic clusters per channel (L1). Each topic has a kind that picks its render.
  // kinds: 'release' | 'event' | 'discussion' | 'metric' | 'question'
  const topics = {
    'ai-twitter': [
      { id: 't1', kind: 'event', title: 'GPT-5 system card leak ripples across timeline', heat: 94,
        summary: 'Partial system card surfaced this afternoon. Reliable accounts treating it as authentic; OpenAI silent. Numbers suggest a step up on coding + agentic benchmarks.',
        meta: '12 mentions · 4 trusted voices · last 2h',
        sources: ['ai-twitter','hn-frontpage','discord-ml'],
        msgs: ['m101','m102','m104','m106','h201','d301'],
        steps: [
          { time: '14:32', text: 'First mention from swyx with screenshot' },
          { time: '14:43', text: 'gdb (OpenAI) declines to comment' },
          { time: '15:02', text: 'Rumor thread consolidates ETA: next Tuesday' },
        ] },
      { id: 't2', kind: 'release', title: 'Anthropic ships Containers API (public beta)', heat: 88,
        summary: 'Sandboxed tool execution environments for Claude. Cold start ~800ms reported. Pricing $0.10/hr active, 50 free hours/month — aggressive vs Modal/Fly/E2B.',
        meta: 'Anthropic · public beta · today',
        tag: 'public beta',
        sources: ['ai-twitter','hn-frontpage','discord-ml','github-issues'],
        msgs: ['m107','m108','m109','h202','h203','d302','g501'] },
      { id: 't3', kind: 'metric', title: 'MCP adoption — 14k servers indexed, +4× in 8 weeks',
        value: '14,182', delta: '+312%', deltaDir: 'up',
        label: 'MCP servers indexed (weekly)',
        spark: [12,14,18,22,28,38,55,82,128,182],
        summary: 'Growth still concentrated in dev tooling but verticals (finance, legal) starting to show. Indexes from third-party directories diverge ±10%.',
        sources: ['ai-twitter','discord-ml'],
        msgs: ['m112','m113','d304'] },
      { id: 't4', kind: 'question', title: 'Open: how do we benchmark agents on dynamic tasks?',
        summary: 'No consensus. GAIA approaching saturation, SWE-bench has leakage concerns. Stanford/DeepMind paper proposes regenerated task specs per run — early reception cautious.',
        meta: 'unresolved · 6 voices · spans 3 channels',
        sources: ['ai-twitter','hn-frontpage','arxiv-daily'],
        msgs: ['m116','m117','h204','a401'] },
      { id: 't5', kind: 'release', title: 'PyTorch 2.6 — compile() 1.7× on H100 inference', heat: 71,
        summary: 'Flash-attention v3 now default, sparse MoE kernels, 184 changes total. Speculative decoding paper implementation included.',
        meta: 'PyTorch · GA · today',
        tag: 'GA',
        sources: ['ai-twitter','arxiv-daily','github-issues'],
        msgs: ['m119','a403','g502'] },
      { id: 't6', kind: 'discussion', title: 'Ambient chatter: API outages, gm/gn, low-signal noise',
        summary: '34 messages of low informational density. Filtered out by default. Includes the recurring "is the api down" thread and weather.',
        meta: '34 messages · all low-priority',
        voices: ['ma','ld','tk','vn','jq','+29'],
        sentiment: { pos: 12, neu: 78, neg: 10 },
        sources: ['ai-twitter'],
        msgs: ['m103','m105','m110','m111','m114','m115','m118','m120'] },
    ],
    'hn-frontpage': [
      { id: 't1', kind: 'event', title: 'GPT-5 leak hits HN front page (#1, 1.2k pts)', heat: 92,
        summary: 'Submission climbed to #1 in 40 min. Mirror link, since the original was DMCAed. Comments are split between skepticism and detailed analysis.',
        meta: '1,204 points · 481 comments',
        sources: ['hn-frontpage'],
        msgs: ['h201'],
        steps: [
          { time: '12:18', text: 'Submitted, climbs to #4' },
          { time: '13:02', text: 'Hits #1 — dang adds noprocrast' },
          { time: '14:11', text: 'Original link DMCAed, mirror keeps post alive' },
        ] },
      { id: 't2', kind: 'discussion', title: 'Containers API — comparing to E2B, Modal, Fly',
        summary: 'Cold-start latency is the main technical concern. Pricing seen as competitive. Lock-in worries from the usual quarters but tone is net-positive.',
        meta: '218 comments · cold-start the top thread',
        voices: ['jt','pa','sg','dh','+38'],
        sentiment: { pos: 58, neu: 32, neg: 10 },
        sources: ['hn-frontpage','discord-ml'],
        msgs: ['h202','h203'] },
      { id: 't4', kind: 'discussion', title: '"Benchmarks are lies" opinion piece climbing',
        summary: 'Opinion piece on eval theatre cites the SWE-bench leakage paper. Polarising — equal applause and pushback in comments.',
        meta: '412 points · 198 comments',
        voices: ['tp','ja','mw','+22'],
        sentiment: { pos: 35, neu: 30, neg: 35 },
        sources: ['hn-frontpage','ai-twitter'],
        msgs: ['h204','m116'] },
    ],
    'discord-ml': [
      { id: 't1', kind: 'discussion', title: 'GPT-5 rumor channel: 240 messages in 2h',
        summary: 'Channel #rumors went from quiet to active. Most messages low-signal but a cluster of researchers analyzing the eval table.',
        meta: '240 messages · 38 unique users',
        voices: ['r4','ag','mc','tk','jq','+33'],
        sentiment: { pos: 22, neu: 64, neg: 14 },
        sources: ['discord-ml','ai-twitter'],
        msgs: ['d301','m101','m102'] },
      { id: 't2', kind: 'release', title: 'Containers API — real cold-start numbers from devs', heat: 80,
        summary: 'Developers reporting consistent 700-900ms cold start, well under typical agent budgets. Several migrations already in progress.',
        meta: 'public beta · ~6 dev reports',
        tag: 'in production',
        sources: ['discord-ml'],
        msgs: ['d302','d303'] },
      { id: 't3', kind: 'metric', title: 'MCP curator log — server adds this week',
        value: '+638', delta: 'this week', deltaDir: 'up',
        label: 'New MCP servers added',
        spark: [40,55,62,78,82,90,120,150,180,210],
        summary: 'GitHub, Notion, Linear leading. Mostly dev tooling, but seeing a tail of vertical-specific servers (compliance, finance ops).',
        sources: ['discord-ml','ai-twitter'],
        msgs: ['d304'] },
    ],
    'arxiv-daily': [
      { id: 't4', kind: 'event', title: 'Dynamic Task Benchmarking paper drops', heat: 64,
        summary: 'Stanford + DeepMind. Proposes regenerating task specs per evaluation run so models cannot memorize the benchmark. Early reception mixed.',
        meta: 'arXiv:2025.0942 · 28 pages',
        sources: ['arxiv-daily','ai-twitter','hn-frontpage'],
        msgs: ['a401','m116','m117'],
        steps: [
          { time: '09:00', text: 'Posted to arXiv (cs.AI)' },
          { time: '11:30', text: 'Picked up by ML Twitter' },
          { time: '15:30', text: 'Tptacek references on HN' },
        ] },
      { id: 't5', kind: 'release', title: 'Speculative decoding — 1.8× on H100 long context', heat: 58,
        summary: 'Implementation drops landing in PyTorch 2.6 (same day). Throughput improvements concentrated on >32k contexts.',
        meta: 'arXiv:2025.0931 · companion to PT 2.6',
        tag: 'implementation shipped',
        sources: ['arxiv-daily','ai-twitter','github-issues'],
        msgs: ['a403','m119','g502'] },
    ],
    'github-issues': [
      { id: 't2', kind: 'event', title: 'Anthropic SDK #4421 — Containers API tracking', heat: 72,
        summary: 'Official tracking issue. 14 reactions in first hour. Top concern: container persistence across sessions.',
        meta: 'anthropics/sdk · #4421',
        sources: ['github-issues','ai-twitter'],
        msgs: ['g501','m107'],
        steps: [
          { time: '12:00', text: 'Issue opened, marked beta-tracking' },
          { time: '12:14', text: 'First thumbs reactions' },
          { time: '12:42', text: 'Maintainer responds re: persistence' },
        ] },
      { id: 't5', kind: 'release', title: 'pytorch/pytorch v2.6.0 tagged', heat: 65,
        summary: '184 changes. Compile() improvements, flash-attn v3 default, sparse MoE kernels. Notes are dense — significant under-the-hood work.',
        meta: 'pytorch/pytorch · v2.6.0',
        tag: 'GA',
        sources: ['github-issues','ai-twitter','arxiv-daily'],
        msgs: ['g502','m119','a403'] },
    ],
  };

  // The L0 deep research report (one per channel)
  const reports = {
    'ai-twitter': {
      title: 'AI/ML signals — afternoon brief',
      eyebrow: 'Deep research · L0',
      generated: '17:24 UTC · 4 channels · 247 messages analysed',
      confidence: 'medium-high',
      coverage: '94%',
      exec: 'Two major events landed within an hour of each other: a credible GPT-5 system card leak and the public-beta release of Anthropic\'s Containers API. The day\'s signal-to-noise was unusually high in the morning, but rumour traffic now dominates and is degrading the feed. MCP infrastructure continues compounding quietly underneath.',
      findings: [
        { num: '01', title: 'GPT-5 leak is probably real but partial', cites: ['t1'],
          body: 'Multiple independent trusted accounts treat the system card as authentic. OpenAI\'s non-denial (gdb: "no comment is a comment") is weak evidence in favour. The eval table appears genuine but is partial — full benchmark coverage is not in the leaked pages. Recommend treating the 400k context + agentic loop claims as load-bearing, the specific eval numbers as directionally correct.' },
        { num: '02', title: 'Containers API is a genuine platform move', cites: ['t2'],
          body: 'Sandboxed tool execution closes the largest reliability gap in agent products. Cold-start latency (~800ms) reported by independent developers is well under typical agent budgets. Pricing undercuts E2B and Modal on the low end. The free tier (50 hrs/month) suggests Anthropic wants developer mindshare more than near-term revenue.' },
        { num: '03', title: 'MCP keeps compounding off-stage', cites: ['t3'],
          body: '14k+ servers indexed, 4× in 8 weeks. Growth is still concentrated in dev tooling but vertical-specific servers (finance, legal, compliance) are showing up consistently in curator logs. This is the kind of growth curve that becomes obvious in retrospect.' },
        { num: '04', title: 'Eval crisis is back on the agenda', cites: ['t4'],
          body: 'Two parallel threads — Stanford/DeepMind\'s dynamic-task paper and a popular HN opinion piece — converged on the same point today: current public benchmarks are saturating or leaking. Internal evals are diverging from headline numbers. Expect a new wave of moving-target eval frameworks within Q3.' },
        { num: '05', title: 'PyTorch 2.6 is more important than its release notes suggest', cites: ['t5'],
          body: '1.7× compile() speedup on H100 inference is significant for production economics. Flash-attn v3 becoming default removes a configuration footgun. Read the release notes carefully — much of the gain is in the un-headlined sparse MoE kernels.' },
      ],
      recs: [
        { badge: 'WATCH', text: 'Pin Tuesday for the GPT-5 announcement window; pre-stage analysis templates.' },
        { badge: 'TRY',   text: 'Stand up a Claude Containers prototype this week — generous free tier, low switching cost.' },
        { badge: 'TRACK', text: 'Subscribe to mcp-curator log; set alert at 20k server threshold.' },
        { badge: 'READ',  text: 'arXiv:2025.0942 (Dynamic Task Benchmarking) — likely to influence next eval cycle.' },
      ],
    },
    'hn-frontpage': {
      title: 'HN front-page brief',
      eyebrow: 'Deep research · L0',
      generated: '17:18 UTC · 38 messages analysed',
      confidence: 'high',
      coverage: '100%',
      exec: 'HN front page is dominated by the GPT-5 leak and the Containers API launch. Discussion quality is high in technical threads, lower in the rumour threads. One opinion piece on eval theatre is climbing and is worth tracking.',
      findings: [
        { num: '01', title: 'GPT-5 leak holds #1 spot', cites: ['t1'],
          body: 'Submission climbed to #1 in 40 minutes. Original DMCAed; mirror kept the discussion alive. Comments are split between skeptics and detailed analyses of the eval table.' },
        { num: '02', title: 'Containers API discussion is net-positive', cites: ['t2'],
          body: 'Cold-start latency is the dominant technical concern. Pricing seen as competitive vs E2B/Modal. Lock-in worries are present but not winning the thread.' },
        { num: '03', title: 'Eval-theatre piece is polarising and worth watching', cites: ['t4'],
          body: 'Opinion piece citing the SWE-bench leakage paper at 412 points. Even split of applause and pushback — usually a leading indicator of an emerging consensus shift.' },
      ],
      recs: [
        { badge: 'WATCH', text: 'Track the eval-theatre piece as it makes top-of-day; the discussion is the real signal.' },
        { badge: 'READ',  text: 'Cold-start latency subthread under Containers API submission.' },
      ],
    },
    'discord-ml': {
      title: 'Discord ML community brief',
      eyebrow: 'Deep research · L0',
      generated: '17:11 UTC · 184 messages analysed',
      confidence: 'medium',
      coverage: '87%',
      exec: 'Channel #rumors is loud and noisy — most messages are low-signal reactions to the GPT-5 leak. Higher-signal traffic is in #agent-builds, where multiple developers report production migrations to Claude Containers within hours of launch.',
      findings: [
        { num: '01', title: 'Containers API already in production for some teams', cites: ['t2'],
          body: 'Six developers reported migrating coding/research agents within the first three hours. Reported cold-start consistently 700–900ms. This is unusually fast adoption for a public-beta product.' },
        { num: '02', title: 'MCP server adds — 638 this week', cites: ['t3'],
          body: 'Curator log shows steady weekly growth. Vertical tail (compliance, finance ops) is starting to thicken. Still dev-tooling dominated.' },
        { num: '03', title: 'Rumor channel is noisy, save your attention', cites: ['t1'],
          body: 'Most messages in #rumors are emotional reactions. A small cluster of researchers analyzing the leaked eval table is the only durable signal — surfaced in t1.' },
      ],
      recs: [
        { badge: 'MUTE',  text: '#rumors until announcement; rejoin then.' },
        { badge: 'WATCH', text: '#agent-builds for Containers adoption patterns.' },
      ],
    },
    'arxiv-daily': {
      title: 'arXiv daily brief',
      eyebrow: 'Deep research · L0',
      generated: '09:14 UTC · 62 papers indexed',
      confidence: 'high',
      coverage: '100%',
      exec: 'Two papers stand out today: a Stanford/DeepMind framework for dynamic agent benchmarks, and a speculative decoding implementation that shipped same-day in PyTorch 2.6. Survey paper on attention is comprehensive but not novel.',
      findings: [
        { num: '01', title: 'Dynamic Task Benchmarking is a real proposal', cites: ['t4'],
          body: 'Regenerated task specs per evaluation run. The implementation details suggest this could be tractable for code-execution and tool-use evals; harder for open-ended reasoning. Worth a careful read.' },
        { num: '02', title: 'Speculative decoding — implementation ships same day', cites: ['t5'],
          body: 'Paper-to-shipped-code latency is unusually short. The 1.8× throughput claim is consistent with similar prior work; novelty is in long-context regime.' },
      ],
      recs: [
        { badge: 'READ',  text: 'arXiv:2025.0942 (Dynamic Task Benchmarking) — full paper.' },
        { badge: 'SKIM',  text: 'arXiv:2025.0931 (Speculative Decoding long context).' },
      ],
    },
    'github-issues': {
      title: 'GitHub issues brief',
      eyebrow: 'Deep research · L0',
      generated: '17:02 UTC · 91 issues touched',
      confidence: 'high',
      coverage: '96%',
      exec: 'Two major events on tracked repos: Anthropic SDK opened the Containers API tracking issue, and PyTorch tagged 2.6.0. Both will dominate downstream discussion for the next 48h.',
      findings: [
        { num: '01', title: 'Anthropic SDK #4421 is the canonical Containers thread', cites: ['t2'],
          body: 'Use this issue as the source-of-truth for known limitations, persistence behavior, and pricing edge cases. Maintainers are actively triaging.' },
        { num: '02', title: 'PyTorch 2.6 release notes are dense', cites: ['t5'],
          body: '184 changes. Headline is compile()-on-H100, but sparse MoE kernel additions and the flash-attn v3 default flip are likely to matter more in production.' },
      ],
      recs: [
        { badge: 'WATCH', text: 'anthropics/sdk#4421 for Containers limitations updates.' },
        { badge: 'AUDIT', text: 'PyTorch 2.6 changes against your inference stack.' },
      ],
    },
  };

  return { channels, messages, topics, reports };
})();
